### ISSUE TITLE
prototype iValt implementation

### ISSUE THREAD

**Issue by KingOfTac** [trans-stat/tas-security#4]
```[tasklist]
### Code Tasks
- [x] Prototype backend API implementation
- [x] Add frontend FAST components
- [ ] Prototype frontend service layer (If any. Needs investigation on proper approach.)
```
```[tasklist]
### Research Tasks
- [x] Find out the best method for passing iValt API key to the backend class instance.
- [x] Determine how the UI elements are going to communicate with the backend in a generic, framework agnostic way.
```

## Engineering Notes

The iValt implementation will be it's own package split into a backend component and frontend elements.

The backend component will be a simple javascript class wrapping the iValt API that can be instantiated. This will allow us to keep the implementation free of any framework opinions and able to be integrated into a wide variety of applications. Investigation needs to be done on how access to the iValt API key will be handled, but the two options currently are: passing the key to the class instance or adding the key to a .env file where the class instance can find it.

The frontend component will have a service class that can be instantiated or injected through a frameworks DI implementation if available. This class will handle the communication with the backend component. Another option here is to just document the API and provide code examples of communicating with the backend component in a couple of scenarios. The frontend component will also export a mini library of FAST components for displaying MFA UI.

The exact architecture of both the backend and frontend components might change once implementation is underway.

**Comment by awentzel** [comment]
This sounds like a good starting point. Are you thinking of JavaScript or TypeScript class? It would be great for the service class to have both implementations and a well-documented API with code examples. Wiring this up with code coverage and complete testing would also be excellent so we know if any regressions were introduced when making changes.

**Comment by KingOfTac** [comment]
Typescript across backend and frontend components.

**Comment by awentzel** [comment]
When will work makes its way into this repo?

**Comment by KingOfTac** [comment]
Prototyping is completed. After testing the implementation I determined that there needs to be some refinement to both the backend and frontend code, but will be tracking those in separate issues.
